# Generated by Django 2.2.16 on 2022-06-04 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genres',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='genres',
        ),
        migrations.AddField(
            model_name='titles',
            name='description',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(related_name='titles', to='reviews.Genres'),
        ),
        migrations.AddField(
            model_name='titles',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.Categories'),
        ),
    ]
